name: "My Action"

description: "Say hello with Github  Actions"


inputs:
  first-greeting:
    description: "Who would like to greet in console"
    required: true
    default: "Hubot"

  second-greeting:
    description: "Another person to greet"
    required: true
    default: "Mona the cat"

  third-greeting:
    description: "A third greeting"
    required: false

runs:
  using: "node12"
  main: "main.js"