name: Release|New/Reopened PR

on:
  pull_request:
    types: [labeled]

jobs:
  chat:
     runs-on: ubuntu-latest
     steps:
       - uses: geored/indy-action@v1
         with:
           gchat-webhooks: ${{ secrets.WEBHOOK_URLS }}
