name: Release|New/Reopened PR

on:
  pull_request:
    types: [labeled]

jobs:
  gchat:
     runs-on: ubuntu-latest
     steps:
       - uses: geored/indy-action@v2
         with:
           gchat-webhooks: ${{ secrets.WEBHOOK_URLS }}
